[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["E", "F", "I"]   # pyflakes/pycodestyle/isort
exclude = ["db/init"]             # ignore les .sql et dossiers DB

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["etl/tests"]
